---
# Ansible playbook to import (or reimport) SNAP:DRGN RDF data into the 4store service.
# Use this playbook outside of vagrant by typing `ansible-playbook provisioning/import-rdf.yml -i provisioning/inventory`

- hosts: snap
  gather_facts: yes
  become: yes

  tasks:
    - name: Stop 4store
      command: systemctl stop 4store
      become: yes

    - name: Setup the 'snap' triplestore
      command: sudo 4s-backend-setup snap
    
    - name: Fix snap data directory permissions
      file:
        path: /var/lib/4store/snap
        owner: fourstore
        group: fourstore
        mode: 0775
        recurse: yes
    
    - name: Start 4store backend daemon (running as the fourstore user)
      command: sudo -H -u fourstore 4s-backend snap

    - name: Import SNAP PIR* rdf data
      shell: 4s-import snap -v -M http://pir /var/www/html/snap/RDF/pir/PIR*
      register: cmdio
    - debug: msg="{{ cmdio.stdout }}"
    - debug: msg="{{ cmdio.stderr }}"

    - name: Import SNAP TM* rdf data
      shell: 4s-import snap -v -M http://tm /var/www/html/snap/RDF/TM/TM*
      register: cmdio
    - debug: msg="{{ cmdio.stdout }}"
    - debug: msg="{{ cmdio.stderr }}"


    - name: Re-start 4store (port 9000)
      command: systemctl start 4store
      become: yes