---
# Ansible playbook to import (or reimport) SNAP:DRGN RDF data into the 4store service.
# Use this playbook outside of vagrant by typing `ansible-playbook provisioning/import-rdf.yml -i provisioning/inventory`

- hosts: snap
  gather_facts: yes
  become: yes
  ignore_errors: yes

  tasks:
    - name: Stop 4store
      command: systemctl stop 4store
      become: yes

    - name: Setup the 'snap' triplestore
      command: sudo 4s-backend-setup snap
    
    - name: Fix snap data directory permissions
      file:
        path: /var/lib/4store/snap
        owner: fourstore
        group: fourstore
        mode: 0775
        recurse: yes
    
    - name: Start 4store backend daemon (running as the fourstore user)
      command: sudo -H -u fourstore 4s-backend snap

    - name: SNAP PIR* IMPORT RDF
      shell: 4s-import snap -v -M http://pir /var/www/html/snap/RDF/pir/PIR*
      register: cmdio
    - name: SNAP PIR* stdout
      debug: msg="{{ cmdio.stdout_lines }}"
    - name: SNAP PIR* stderr
      debug: msg="{{ cmdio.stderr_lines }}"

    - name: SNAP TM* IMPORT RDF
      shell: 4s-import snap -v -M http://tm /var/www/html/snap/RDF/TM/TM*
      register: cmdio
    - name: SNAP TM* stdout
      debug: msg="{{ cmdio.stdout_lines }}"
    - name: SNAP TM* stderr
      debug: msg="{{ cmdio.stderr_lines }}"

    - name: SNAP bm* IMPORT RDF
      shell: 4s-import snap -v -M http://bm /var/www/html/snap/RDF/bm/bm*
      register: cmdio
    - name: SNAP bm* stdout
      debug: msg="{{ cmdio.stdout_lines }}"
    - name: SNAP bm* stderr
      debug: msg="{{ cmdio.stderr_lines }}"

    - name: SNAP viaf* IMPORT RDF
      shell: 4s-import snap -v -M http://viaf /var/www/html/snap/RDF/viaf/viaf*
      register: cmdio
    - name: SNAP viaf* stdout
      debug: msg="{{ cmdio.stdout_lines }}"
    - name: SNAP viaf* stderr
      debug: msg="{{ cmdio.stderr_lines }}"

    - name: SNAP lgpn* IMPORT RDF
      shell: 4s-import snap -v -M http://lgpn /var/www/html/snap/RDF/lgpn/lgpn*
      register: cmdio
    - name: SNAP lgpn* stdout
      debug: msg="{{ cmdio.stdout_lines }}"
    - name: SNAP lgpn* stderr
      debug: msg="{{ cmdio.stderr_lines }}"

    - name: Re-start 4store (port 9000)
      command: systemctl start 4store
      become: yes